"""add_xz

Revision ID: 6bad7b7ccdae
Revises: 02935c7057a6
Create Date: 2026-04-24 13:45:50.338242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bad7b7ccdae'
down_revision: Union[str, Sequence[str], None] = '02935c7057a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topups', sa.Column('rate_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topups', 'rate_usd')
    # ### end Alembic commands ###
