"""add_stats_daily_and_products

Revision ID: 7f87836a26d2
Revises: 6bb0b7aecdb1
Create Date: 2026-04-30 02:38:44.424854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f87836a26d2'
down_revision: Union[str, Sequence[str], None] = '6bb0b7aecdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'metric_name', name='uq_daily_metric')
    )
    op.create_index(op.f('ix_stats_daily_metric_name'), 'stats_daily', ['metric_name'], unique=False)
    op.create_index(op.f('ix_stats_daily_stat_date'), 'stats_daily', ['stat_date'], unique=False)
    op.create_table('stats_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('qty_sold', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'period_start', 'period_end', name='uq_product_period')
    )
    op.alter_column('stats_cache', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats_cache', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('stats_products')
    op.drop_index(op.f('ix_stats_daily_stat_date'), table_name='stats_daily')
    op.drop_index(op.f('ix_stats_daily_metric_name'), table_name='stats_daily')
    op.drop_table('stats_daily')
    # ### end Alembic commands ###
