"""add_topups_table

Revision ID: 4d83d9eab641
Revises: 1e42df6abe12
Create Date: 2026-04-24 11:41:14.020465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d83d9eab641'
down_revision: Union[str, Sequence[str], None] = '1e42df6abe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('amount_usdt', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topups')
    # ### end Alembic commands ###
