"""add_payment_method_column

Revision ID: e6ae41b27f06
Revises: 0b69cae21003
Create Date: 2026-04-29 03:32:09.734158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ae41b27f06'
down_revision: Union[str, Sequence[str], None] = '0b69cae21003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.alter_column('payments', 'invoice_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('payments', 'invoice_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'invoice_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('payments', 'invoice_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
